# Netlify configuration for GenieFlowAI
# Documentation: https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  command = "npm run build"
  publish = "dist"  # Vite's default output directory

# Handle SPA routing by redirecting all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Enable HTTPS and security headers
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.googletagmanager.com https://*.firebase.googleapis.com https://*.google.com https://apis.google.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https: blob:; media-src 'self' data: blob:; connect-src 'self' https://*.genieflowai.com https://*.supabase.co https://*.googleapis.com https://*.google.com https://*.firebaseio.com https://*.firebaseapp.com https://*.firebaseinstallations.googleapis.com https://*.firebase.googleapis.com https://*.firebaselogging.googleapis.com https://*.googletagmanager.com https://*.identitytoolkit.googleapis.com https://*.securetoken.googleapis.com https://*.gmail.googleapis.com https://*.mail.google.com https://*.accounts.google.com; font-src 'self' data:; frame-src 'self' blob: https://*.google.com https://*.firebaseapp.com; frame-ancestors 'none'; form-action 'self' https://*.google.com; object-src 'none';"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Environment variables should be set in Netlify UI, not here
[context.production.environment]
  NODE_ENV = "production"
  VITE_USE_MOCK = "false"

# Environment variables for branch deployments
[context.branch-deploy.environment]
  NODE_ENV = "production"
  VITE_USE_MOCK = "false"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9" 