# Netlify configuration for GenieFlowAI
# Documentation: https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  command = "npm run build"
  publish = "dist"  # Vite's default output directory

# Handle SPA routing by redirecting all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Enable HTTPS and security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' 
        https://apis.google.com 
        https://www.gstatic.com 
        https://www.google-analytics.com 
        https://www.googletagmanager.com
        https://tagmanager.google.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      img-src 'self' data: https: http:;
      font-src 'self' https://fonts.gstatic.com;
      connect-src 'self' 
        https://api.genieflowai.com 
        https://*.supabase.co 
        https://generativelanguage.googleapis.com 
        https://www.googleapis.com 
        https://oauth2.googleapis.com 
        https://firebaseinstallations.googleapis.com
        https://*.firebase.googleapis.com 
        https://*.firebaseio.com 
        https://identitytoolkit.googleapis.com 
        https://securetoken.googleapis.com 
        https://firebaselogging.googleapis.com
        https://*.googleapis.com
        https://*.google-analytics.com
        https://*.analytics.google.com
        wss://*.firebaseio.com
        https://firebase.googleapis.com
        https://firebaseinstallations.googleapis.com
        https://www.googletagmanager.com;
      frame-src 'self' https://*.google.com;
      media-src 'self' https: http:;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
      frame-ancestors 'none';
      upgrade-insecure-requests;
    """

# Environment variables should be set in Netlify UI, not here
[context.production.environment]
  NODE_ENV = "production"
  VITE_USE_MOCK = "false"

# Environment variables for branch deployments
[context.branch-deploy.environment]
  NODE_ENV = "production"
  VITE_USE_MOCK = "false"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9" 