# Netlify configuration for GenieFlowAI
# Documentation: https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  command = "npm run build"
  publish = "dist"  # Vite's default output directory

# Handle SPA routing by redirecting all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Enable HTTPS and security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval';
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https:;
      connect-src 'self' 
        https://api.genieflowai.com 
        https://*.supabase.co 
        https://generativelanguage.googleapis.com 
        https://www.googleapis.com 
        https://oauth2.googleapis.com;
      font-src 'self' data:;
      frame-ancestors 'none';
      form-action 'self';
    """

# Environment variables should be set in Netlify UI, not here
[context.production.environment]
  NODE_ENV = "production"
  VITE_USE_MOCK = "false"

# Environment variables for branch deployments
[context.branch-deploy.environment]
  NODE_ENV = "production"
  VITE_USE_MOCK = "false"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["serverless-http", "express", "cors", "dotenv", "nodemailer", "imap", "mailparser", "googleapis"]

# Configure all functions to use ESM format
[functions."*"]
  node_bundler = "esbuild"
  format = "esm"

# API redirects to Netlify Functions
[[redirects]]
  from = "/api/email/*"
  to = "/.netlify/functions/email/api/email/:splat"
  status = 200

[[redirects]]
  from = "/api/feedback"
  to = "/.netlify/functions/feedback/api/feedback"
  status = 200

[[redirects]]
  from = "/api/train/*"
  to = "/.netlify/functions/train/api/train/:splat"
  status = 200 