# Netlify configuration for GenieFlowAI Production
# Documentation: https://docs.netlify.com/configure-builds/file-based-configuration/
# Last updated: April 30, 2025 - Standardized build output directory

[build]
  command = "npm run build"
  publish = "build"  # Matches Vite's output directory in vite.config.js

# Production environment variables
[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  VITE_APP_ENV = "production"
  VITE_SUPABASE_URL = "https://bpczmzsozjlqxercmnyu.supabase.co"
  VITE_AUTH_CALLBACK_URL = "https://genieflowai.com/auth/callback"
  VITE_USE_MOCK = "false"

# Enable built-in performance optimization
[build.processing]
  skip_processing = false

[build.processing.css]
  minify = true
  
[build.processing.js]
  minify = true
  
[build.processing.html]
  pretty_urls = true
  
[build.processing.images]
  compress = true

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["serverless-http", "express", "cors", "dotenv", "nodemailer", "imap", "mailparser", "googleapis"]

# Configure all functions to use ESM format
[functions."*"]
  node_bundler = "esbuild"
  format = "esm"

# API redirects to Netlify Functions
[[redirects]]
  from = "/api/email/*"
  to = "/.netlify/functions/email/api/email/:splat"
  status = 200

[[redirects]]
  from = "/api/feedback"
  to = "/.netlify/functions/feedback/api/feedback"
  status = 200

[[redirects]]
  from = "/api/train/*"
  to = "/.netlify/functions/train/api/train/:splat"
  status = 200

# Handle SPA routing by redirecting all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Add cache headers for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Enable HTTPS and security headers for all files
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Cross-Origin-Opener-Policy = "same-origin-allow-popups"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://apis.google.com https://accounts.google.com;
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https: blob:;
      connect-src 'self' 
        https://api.genieflowai.com 
        https://*.supabase.co 
        https://generativelanguage.googleapis.com 
        https://api.openai.com
        https://api.anthropic.com
        https://www.googleapis.com 
        https://oauth2.googleapis.com;
      font-src 'self' data:;
      media-src 'self' blob:;
      worker-src 'self' blob:;
      frame-ancestors 'none';
      form-action 'self';
      base-uri 'self';
      upgrade-insecure-requests;
    """