# Netlify configuration for GenieFlowAI
# Documentation: https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  command = "npm ci && npm install -g typescript && npm run build"
  publish = "dist"  # Vite's default output directory

# Handle SPA routing by redirecting all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Enable HTTPS and security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
    Content-Security-Policy = '''
      default-src 'self' https://*.supabase.co https://*.supabase.io https://*.sentry.io;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.netlify.app;
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: blob: https://*.netlify.app https://*.gravatar.com https://*.googleusercontent.com https://ui-avatars.com;
      font-src 'self' data:;
      connect-src 'self' https://oauth2.googleapis.com https://*.googleapis.com https://*.google.com https://*.supabase.co https://*.supabase.io wss://*.supabase.co https://*.sentry.io;
      frame-src 'self' https://accounts.google.com;
      object-src 'none';
      base-uri 'self';
      form-action 'self' https://accounts.google.com;
    '''

# Environment variables should be set in Netlify UI, not here
[context.production.environment]
  NODE_ENV = "production"
  VITE_USE_MOCK = "false"

# Environment variables for branch deployments
[context.branch-deploy.environment]
  NODE_ENV = "production"
  VITE_USE_MOCK = "false"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10" 