# Netlify configuration for GenieFlowAI
# Documentation: https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  command = "npm run build"
  publish = "build"

# Handle SPA routing by redirecting all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Enable HTTPS and security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://api.genieflowai.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://api.genieflowai.com; font-src 'self'; frame-src 'self'; object-src 'none'"

# Set environment variables for production
[context.production.environment]
  NODE_ENV = "production"
  
# Set environment variables for branch deployments (preview)
[context.branch-deploy.environment]
  NODE_ENV = "production"
  REACT_APP_API_URL = "https://api-staging.genieflowai.com" 